### ISSUE TITLE
Fails with components

### ISSUE THREAD

**Issue by Mark2Mark** [mekkablue/MagicRemove#3]
```py
Traceback (most recent call last):
  File "plugin.py", line 131, in eraseSelectedItemsOnAllMasters_
    thisLayer.removeComponentAtIndex_(componentIndex)
AttributeError: 'GSLayer' object has no attribute 'removeComponentAtIndex_'
```

**Comment by schriftgestalt** [comment]
Are you sure you have the latest versions of the plugin?

**Comment by Mark2Mark** [comment]
Yes. It’s the same in 3177 and in 3151 (which I still use because the `startDrag`/`startDragg` issue still occurs in 3177)

**Comment by schriftgestalt** [comment]
because the current source code in this repos doesn't mention `thisLayer.removeComponentAtIndex_` (at least I don’t see it).

**Comment by Mark2Mark** [comment]
ah, you meant the plugin. Didn’t check, as I expected the updates to happen automatically.

I uninstalled it and restarted Glyphs. Now it works. Seems to have fetched the latest version now.
